### ISSUE TITLE
Библиотека не запускается

### ISSUE THREAD

**Issue by dura0ok** [LoginovIlya/words-to-numbers#1]
Операционная система: Ubuntu 18.04, php7.3
PHP Fatal error:  Uncaught Error: Class 'WordsToNumbers\WordsToNumbers' not found in /home/stepan7/asd/index.php:7
Stack trace:
#0 {main}
  thrown in /home/stepan7/asd/index.php on line 7
Вот [Код](https://pastebin.com/R6yEHF9a)
![Снимок экрана от 2019-10-16 06-31-57](https://user-images.githubusercontent.com/28489754/66886005-b467f200-efde-11e9-85d0-28ed50564afd.png)
В чем может быть проблема?

**Comment by LoginovIlia** [comment]
Была небольшая опечатка в autoload секции composer. Уже поправил, можете обновляться. Если вы решите установить ее заново, не забудьте флаг --no-cache, чтобы скачалась новая версия 1.0.1
